### ISSUE TITLE
Main content's text and text in dropdown overlapping

### ISSUE THREAD

**Issue by AceKiron** [AxolotlAPI/axolotls#5]
Currently I'm working on a dropdown, but the text of the main content overlaps with the text in the dropdown and I have no idea why.
I already asked in a Discord server, where someone mentioned having to add a z-index, but that didn't seem to fix it.

**Comment by MaPhiKo** [comment]
`#search-bar {
	background-color: var(--secondary-accent-background-color);

	position: absolute;
	left: 0;
	top: 40px;
	width: 100%;

	//z-index: -1;

	box-shadow: 0px 0px 8px var(--accent-box-shadow-color);
}`
The #search-bar has a negative z-index. Given that the dropdown is its child, removing the negative z-index here should fix the issue.

**Comment by AceKiron** [comment]
Unfortunately your approach didn't seem to fix the issue, but giving `#wrapper` a z-index of -1000 did fix it.
